-d D:\GoWin\lab4\impl\gwsynthesis\lab4.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst D:\GoWin\lab4\src\lab4.cst
-cfg D:\GoWin\lab4\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
