-d D:\GoWin\lab4_spi\impl\gwsynthesis\lab4_spi.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst D:\GoWin\lab4_spi\src\lab4_spi.cst
-cfg D:\GoWin\lab4_spi\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
